import Head from "next/head";
import { Footer, Header, Highlight } from "../components";
import { Container } from "../styles/pages/Home";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>MKS - Sistemas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Highlight />
      <Footer />
    </Container>
  );
}
